Made it last 14 days
JonathanTheZero/Utopia pull request #50
Opened 2020-12-16 21:16 UTC by blitzwolfz

2020-12-16 22:41 UTC, DevilJamJar requested changes

2020-12-16 22:41 UTC, DevilJamJar commented on src/commands/giveaways.ts
> +    if (addTime > (20160*60000)) return message.reply("You can't start a giveaway that lasts longer than two days!");
Dude if you’re gonna change it at least change the return message

2020-12-16 22:42 UTC, DevilJamJar commented on src/commands/giveaways.ts
> +    if (addTime > (20160*60000)) return message.reply("You can't start a giveaway that lasts longer than two days!");
```suggestion
    if (addTime > (20160*60000)) return message.reply("You can't start a giveaway that lasts longer than fourteen days!");
```

2020-12-16 22:45 UTC, DevilJamJar requested changes
Make return message match

2020-12-23 19:09 UTC, JonathanTheZero requested changes
What Devil said... please change the return message

2020-12-23 19:41 UTC, blitzwolfz commented
ok

2023-01-30 10:28 UTC, closed without merging